### ISSUE TITLE
Setup AppVeyor

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew-release#6]
Since this is really a CLI tool that may be run by Windows users too.

**Comment by LaurentGoderre** [comment]
You just want to test it on Windows CI? It only relies on node and git which are abstracted out of the OS so I am not sure it is essential to test in Windows.

**Comment by nschonni** [comment]
Yeah, we don't have to, but CLI tools tend to find all the fun OS specific (fs, path, network, etc...) issues :wink:

**Comment by LaurentGoderre** [comment]
Fortunately it doesn't really deal with path or anything, everything is at root or abstracted to git.
